apiVersion: service.binding/v1alpha2
kind: ServiceBinding
metadata:
  name: servicebinding-sample
spec:
  service:
    name: pg-instance
    apiVersion: postgresql.example.dev/v1alpha1
    kind: Database
  application:
    name: nodejs-rest-http-crud
    apiVersion: apps/v1
    Kind: Ddeployment
